# global settings
title: "PLATEAU Workshop"
description: "Bringing together Programming Languages and Human-Computer Interaction"
url: "https://schasins.com/plateau/" # the base hostname & protocol for your site, e.g. http://example.com

# build settings
exclude: ["readme.md"]

sass:
  # Where you keep your scss files
  sass_dir: assets/css/

plugins:
  - jekyll-redirect-from

navbar_links:
  - title: "Home"
    url: "/"
    newtab: false
  - title: "Registration"
    url: "/registration"
    newtab: false
  - title: "Program"
    url: "/program"
    newtab: false